In [2]:
num_list = [1, 2, 3, 4, 5]
for i in num_list:
    print(i)

1
2
3
4
5


In [3]:
itr = iter(num_list)
print(next(itr))

1


In [5]:
print(next(itr))

print(next(itr))

3
4


In [6]:
start = 1
stop = 6.7
step = 0.1

import numpy as np

np.arange(start, stop, step)


array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6])

In [7]:
from numpy import arange

print("Float range using NumPy arange():")

print("\nTest 1:")
for i in arange(0.0, 10.0, 0.5):
    print(i, end=', ')

print("\n\nTest 2:")
for i in arange(0.5, 5.5, 0.5):
    print(i, end=', ')

print("\n\nTest 3:")
for i in arange(-1.0, 1.0, 0.5):
    print(i, end=', ')

Float range using NumPy arange():

Test 1:
0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 

Test 2:
0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 

Test 3:
-1.0, -0.5, 0.0, 0.5, 

In [8]:


import numpy as np
 
print("Print Float Range Using NumPy LinSpace()\n")

print(np.linspace(1.0, 5.0, num = 5))
print(np.linspace(0, 10, num = 5, endpoint = False))


Print Float Range Using NumPy LinSpace()

[1. 2. 3. 4. 5.]
[0. 2. 4. 6. 8.]


In [9]:
from itertools import islice, count

def iter_range(start, stop, step):
    if step == 0:
        raise ValueError("Step could not be NULL")
    length = int(abs(stop - start) / step)
    return islice(count(start, step), length)

for it in iter_range(0, 10, 1.10):
    print ("{0:.1f}".format(it), end = " ")

0.0 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 

In [15]:


from itertools import groupby

things = [("animal", "bear"), ("animal", "duck"), ("plant", "cactus"),("vehicle", "speed boat"), ("vehicle", "school bus")]

for key, group in groupby(things, lambda x: x[0]):
    for thing in group:
        print("A %s is a %s." % (thing[1], key))
    print()

A bear is a animal.
A duck is a animal.

A cactus is a plant.

A speed boat is a vehicle.
A school bus is a vehicle.

