In [1]:
matrix(cbind(1:5, 3:7), 5, 2)

[,1] [,2]
[1,] 1    3   
[2,] 2    4   
[3,] 3    5   
[4,] 4    6   
[5,] 5    7

In [14]:
for(i in 1:4){
    cat(names(iris[i]), "\n mean=", mean(iris[, i]), "\n")
}

Sepal.Length 
 mean= 5.843333 
Sepal.Width 
 mean= 3.057333 
Petal.Length 
 mean= 3.758 
Petal.Width 
 mean= 1.199333 


In [7]:
names(iris[i])

[1] "Sepal.Length"

In [ ]:
# обращение ко всему столбцу 
iris[i]

In [ ]:
# обращение к элементам столбца
iris[, i]

# для образение к таблице [, ]
# для обращение к вектору [[]]

In [15]:
for(i in names(iris)){
    cat(i, "\n mean=", mean(iris[, i]), "\n" )
}

Sepal.Length 
 mean= 5.843333 
Sepal.Width 
 mean= 3.057333 
Petal.Length 
 mean= 3.758 
Petal.Width 
 mean= 1.199333 


Warning message in mean.default(iris[, i]):
“argument is not numeric or logical: returning NA”

Species 
 mean= NA 


In [17]:
sapply(iris, is.numeric)

Sepal.Length  Sepal.Width Petal.Length  Petal.Width      Species 
        TRUE         TRUE         TRUE         TRUE        FALSE

In [24]:
n <- sapply(iris, is.numeric)
for (i in names(iris[n])){
        cat(i, "\n mean=", mean(iris[, i]), "\n" )
}

Sepal.Length 
 mean= 5.843333 
Sepal.Width 
 mean= 3.057333 
Petal.Length 
 mean= 3.758 
Petal.Width 
 mean= 1.199333 


In [26]:
t(apply(iris[n], 2, mean))

Sepal.Length Sepal.Width Petal.Length Petal.Width
[1,] 5.843333     3.057333    3.758        1.199333

In [36]:
n <- sapply(iris, is.numeric)
# cat лучше print
for (i in iris[n]){
    cat("mean=", mean(i), "\n" )
    cat("sd=", format(sd(i), dig=2), "\n")
}

mean= 5.843333 
sd= 0.83 
mean= 3.057333 
sd= 0.44 
mean= 3.758 
sd= 1.8 
mean= 1.199333 
sd= 0.76 


In [37]:
tt <- t.test(rnorm(20))

In [39]:
for(i in tt){
    print(i)
}

         t 
-0.7473922 
df 
19 
[1] 0.463977
[1] -0.4916342  0.2329090
attr(,"conf.level")
[1] 0.95
 mean of x 
-0.1293626 
mean 
   0 
[1] 0.1730853
[1] "two.sided"
[1] "One Sample t-test"
[1] "rnorm(20)"


In [46]:
x <- sample(1:6, 10, rep=T)

In [47]:
t(x)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 5    5    2    6    3    3    6    4    3    5

In [48]:
x[x%%2==0]

[1] 2 6 6 4

In [58]:
x <- sample(2:5, 25, rep=T)
res <- c('зачтено', 'не зачтено')
res[ifelse(x>2, 1, 2)]

[1] "зачтено"    "зачтено"    "зачтено"    "не зачтено" "зачтено"   
 [6] "не зачтено" "зачтено"    "зачтено"    "зачтено"    "не зачтено"
[11] "зачтено"    "зачтено"    "не зачтено" "зачтено"    "зачтено"   
[16] "не зачтено" "не зачтено" "зачтено"    "зачтено"    "не зачтено"
[21] "зачтено"    "зачтено"    "зачтено"    "зачтено"    "зачтено"

In [85]:
res <- c('не зачтено', 'зачтено')
x <- sample(2:5, 25, rep=T)
res[(x>2)+1]

[1] "не зачтено" "зачтено"    "зачтено"    "зачтено"    "зачтено"   
 [6] "не зачтено" "зачтено"    "зачтено"    "зачтено"    "зачтено"   
[11] "зачтено"    "зачтено"    "зачтено"    "зачтено"    "зачтено"   
[16] "зачтено"    "не зачтено" "зачтено"    "не зачтено" "зачтено"   
[21] "не зачтено" "зачтено"    "зачтено"    "зачтено"    "не зачтено"

In [78]:
aa <- cbind(1:5, 3:7)
aa

[,1] [,2]
[1,] 1    3   
[2,] 2    4   
[3,] 3    5   
[4,] 4    6   
[5,] 5    7

In [79]:
apply(aa, 2, sd)

[1] 1.581139 1.581139

In [80]:
cor(aa)

[,1] [,2]
[1,] 1    1   
[2,] 1    1

In [82]:
test <- function (x){
    if(sd(x) > 0){
        t.test(x~c('a', 'a', 'a', 'b', 'b'))$p.value
    }
}
apply(aa, 2, test)

[1] 0.04941626 0.04941626

In [83]:
aa <- cbind(1:5, 6)
apply(aa, 2, test)

[[1]]
[1] 0.04941626

[[2]]
NULL

In [86]:
x <- sample(2:5, 25, rep=T)
ifelse(x>2, 'зачтено', 'не зачтено')

[1] "зачтено"    "зачтено"    "зачтено"    "не зачтено" "зачтено"   
 [6] "зачтено"    "зачтено"    "зачтено"    "не зачтено" "зачтено"   
[11] "не зачтено" "зачтено"    "не зачтено" "не зачтено" "зачтено"   
[16] "зачтено"    "зачтено"    "зачтено"    "зачтено"    "не зачтено"
[21] "зачтено"    "зачтено"    "не зачтено" "зачтено"    "зачтено"

In [92]:
chet <- function(x){
    n <- 0
    for(i in x){
        if(i%%2 == 0){
            n <- n+1
        }
    }
    return(paste("n=", n))
}

In [93]:
chet(x)

[1] "n= 15"

In [95]:
sum(x%%2 == 0)

[1] 15