In [1]:
import numpy as np

На вход подаётся список чисел (строка, где числа разделены запятой).

Создайте и сохраните:

- в переменную V1 Numpy вектор из этих чисел в том же порядке
- в переменную V2 Numpy вектор, содержащий только предпоследнее число (это должен быть именно вектор!)
- в переменную V3 Numpy вектор из этих чисел в обратном порядке
- в переменную V4 Numpy вектор из этих чисел, начиная с 0-ого, через 2 (т.е. каждое третье число)
- в переменную V5 Numpy вектор, созданный из генератора Range, содержащий столько элементов, сколько было передано чисел на вход

In [4]:
x = [float(x) for x in input("Enter multiple value: ").split(',')]

Enter multiple value: 1, 2, 3, 4, 5.0, 6, 7, 8, 9, 10


In [6]:
v1 = np.array(x)
v1

In [15]:
v2 = np.array([x[-2]])
v2

array([9.])

In [10]:
v3 = np.array(x[::-1])
v3

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [12]:
v4 = np.array(x[0::3])
v4

array([ 1.,  4.,  7., 10.])

In [13]:
v5 = np.array(range(len(x)))
v5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

На вход подаётся 2 списка целых чисел (они представляют из себя вектора равной длины, т.е. с одинаковым количеством элементов).

Используя векторные операции создайте и сохраните:

- в переменную V1 Numpy вектор с числами из 1 строки
- в переменную V2 Numpy вектор с числами из 2 строки
- в переменную V3 Numpy вектор с покоординатными суммами V1 и V2
- в переменную V4 Numpy вектор с покоординатными произведениями каждого второго числа V1 на каждое второе число V2, развёрнутого в обратном порядке

In [25]:
V1 = np.fromstring(input(), dtype=int, sep=', ')
V2 = np.fromstring(input(), dtype=int, sep=', ')

1, 2, 3, 4
10, 20, 30, 40


In [26]:
V3 = V1+V2
V3

array([11, 22, 33, 44])

In [29]:
V4 = V1[::2] * V2[::-2]
V4

array([40, 60])

На вход подаётся 2 набора целых чисел.

Создайте вектор V такой, что он будет содержать числа из 1 набора, делящиеся нацело на предпоследнее число из 2 набора и разделённые на это число.

Если таких чисел не найдётся, то вектор V будет пустым (т.е. не будет содержать элементов).

In [37]:
V1 = np.fromstring(input(), sep=',', dtype=int)
V2 = np.fromstring(input(), sep=',', dtype=int)[-2]
V = V1[V1 % V2 == 0] / V2

1, 2, 3, 4, 5, 6
1, 2, 3, 4


In [38]:
V

array([1., 2.])

In [53]:
def len_a(a1, a2):
    #длина отрезка по координатам точек a1(x1, y1) и a2(x2, y2)
    #((a1[0] - a2[0])**2 + (a1[1] - a2[1])**2) ** 0.5
    return sum((a1-a2)**2)**0.5 

A1 = np.array((-1, 1))
A2 = np.array((2, 5))
A3 = np.array((5, -3))

# пл. треугольника по формуле герона
a = len_a(A1, A2)
b = len_a(A2, A3)
c = len_a(A1, A3)

p = (a + b + c) / 2

S = (p * (p - a) * (p - b) * (p - c)) ** 0.5

print(S)

17.999999999999993


Переменная M1 содержит Numpy матрицу.

Произведите операции последовательно:

1. Замените значения в предпоследней строке на значения по формуле:

$sin(x*π/6)$, где x - старое значение

2. Замените значения в предпоследнем столбце на значения по формуле:

$e^x$

 

Примечание. Для ячейки на пересечении предпоследнего столбца и предпоследней строки значение ячейки будет изменено по формуле: 

$e^$$(sin(x*π/6))$

 

Результат запишите в переменную M2

In [69]:
M1 = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))

In [75]:
M2 = M1.copy()
M2[-2] = np.sin(M2[-2]*np.pi/6)
M2[:, -2] = np.exp(M2[:, -2])