In [1]:
import numpy as np

In [2]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/talverinat/.conda/envs/pythonProject/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/talverinat/.conda/envs/pythonProject/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/talverinat/.conda/envs/pythonProject/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/talverinat/.conda/envs/pythonProject/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/talverinat/.conda/envs/pythonProject/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/talverinat/.conda/envs/pythonProject/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/talverinat/.conda/envs/pythonProject/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include

In [4]:
print(np.__version__)

1.19.2


# 3
Считайте число n

Создайте в переменной Z Numpy вектор из нулей длины n.

In [5]:
n = int(input())
Z = np.zeros(n)
print(Z)

5
[0. 0. 0. 0. 0.]


# 3.1

Считайте строку, где значения заданы через пробел shape и dtype

Последнее значение в строке может быть либо числом (тогда это последнее значение кортежа shape, либо строкой dtype)

- shape - атрибут, задающий размеры матрицы нолей (позволяет вернуть вектор-строку, вектор-столбец, матрицу, куб и т.д.)
- dtype - тип данных, использующихся для значений матрицы. По-умолчанию используется numpy.float64.

Создайте матрицу Z размера shape, со значениями типа dtype (если dtype не указан, используйте numpy.float64)

- 5
- 2 3 bool
- 4 int

In [60]:
n = input().split()

if n[-1].isdigit() == False:
    d_type = n[-1]
    shape = [int(i) for i in n[:len(n)-1]]
else:
    shape = [int(i) for i in n]
    d_type = np.float64
    
Z = np.zeros(shape=shape, dtype = d_type)

In [65]:
args = input().split()

try:
    Z = np.zeros(tuple(map(int, args)))
except ValueError:
    Z = np.zeros(tuple(map(int, args[:-1])), args[-1])

4 int


In [ ]:
params = input().split()
t = 'float64' if params[-1].isdigit() else params.pop()
Z = np.zeros(tuple(map(int, params)), dtype=t)

# 4

Посчитайте размер матрицы Z в байтах и выведите его на печать.

Чтобы узнать размер (в байтах) 1 элемента матрицы используйте атрибут https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ndarray.itemsize.html

In [69]:
Z = np.zeros((10,10))
# Z = np.array([1,2,3], dtype=np.float64)

In [70]:
print(Z.itemsize*Z.size)
print(np.prod(Z.shape) * Z.itemsize)
print(Z.nbytes)

800
800
800


# 5

Выведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array.

In [75]:
np.info(np.add)
np.info(np.array)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# 6

Считайте 2 числа:

- n - размер Numpy вектора 
- x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора должны быть равны 0.

Сохраните вектор в переменную Z.

n = 10
x = 4

In [76]:
n = int(input())
x = int(input())
Z = np.zeros(n)
Z[x] = 1

10
4


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [77]:
Z = np.zeros(int(input()))
Z[int(input())] = 1

10
4


# 7

Считайте 2 числа n, m.

Создайте вектор Z состоящий из чисел от n до m с шагом 1.

n = 10 

m = 50

In [78]:
n, m = int(input()), int(input())
Z = np.array(range(n, m+1))

10
50


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
Z = np.arange(int(input()), int(input()) + 1)

# 8

Дан вектор Z

"Разверните" его.

In [79]:
Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
Z

array([4, 3, 2, 1])

In [80]:
Z = np.flip(Z, 0)

In [81]:
Z

array([1, 2, 3, 4])

# 9 

Считайте 3 числа:

- n - количество элементов матрицы
- m и k - размеры матрицы (число строк и столбцов соответственно)

Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).

Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.

In [90]:
n = int(input())
m, k = map(int,input().split())

Z = np.arange(n).reshape((m, k))

6
2 3


In [91]:
Z

array([[0, 1, 2],
       [3, 4, 5]])

# 10.1

Дан вектор Z

Запишите в переменную NonZerros индексы ненулевых элементов.

Используйте функцию https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html?highlight=nonzero#numpy.nonzero

In [95]:
Z = np.array([1, 0, 2, 0, 3, 0, 4])
NonZerros = np.nonzero(Z)

(array([0, 2, 4, 6]),)

# 10.2

Дана матрица чисел Z (Z может быть 1, 2 или даже 3 мерной).

Выведите на печать список чисел из этой матрицы, которые больше 3.

In [98]:
Z = np.array([1, 2, 3, 4])
Z2 = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [0, 0, 9]])
Z3 = np.array([[[1, 2],
               [4, 5]],
              [[7, 8],
               [0, 0]]])

print(list(Z[Z>3]))
print(list(Z2[Z2>3]))
print(list(Z3[Z3>3]))

[4]
[4, 5, 6, 7, 8, 9, 9]
[4, 5, 7, 8]


# 11

Считайте число n

Создайте единичную матрицу размера n, сохраните результат в переменную Z.

https://numpy.org/doc/stable/reference/generated/numpy.eye.html?highlight=numpy%20eye#numpy.eye

In [101]:
n = int(input())
Z = np.eye(n)
Z

3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 12

Считайте 3 числа: n, m, l.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)

Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и сохраните результат в переменную Z.

In [104]:
np.random.seed(42)
n, m, l = map(int,input().split())
Z = np.random.random_sample((n, m, l))

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848]],

       [[0.15601864, 0.15599452],
        [0.05808361, 0.86617615]]])

# 13

Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)

Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).

In [107]:
n, m = map(int, input().split())
np.random.seed(42)
Z = np.random.random_sample((n, m))
print(np.min(Z))
print(np.max(Z))

2 6
0.020584494295802447
0.9699098521619943


# 14

Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)

Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение среднего для всей матрицы.

In [108]:
n, m = map(int, input().split())
np.random.seed(42)
Z = np.random.random_sample((n, m))
print(np.mean(Z))

30 30
0.4923750160905882


# 14.2

Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)

Создайте матрицу n*m из случайных чисел (от 0 до 1).
Найдите среднее значение для каждого из столбцов.
Выведите на печать значение минимального и максимального среднего по столбцам (каждое с новой строки).

ПРИМЕР

[Image: https://ucarecdn.com/3365e7de-3640-463c-8e48-3bc4a0668413/]

- 0.15, 0.55 и 0.88 - средние значения по столбцам.
- 0.15 - минимальное среднее
- 0.88 - максимальное среднее


Используйте атрибут axis функции https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.mean.html

In [111]:
n, m = map(int, input().split())
np.random.seed(42)
Z = np.random.random_sample((n, m))
my_mean = np.mean(Z, axis = 0)
print(np.min(my_mean))
print(np.max(my_mean))

3 4
0.270220682758469
0.8115814940446553


# 15

Считайте 2 числа: n, m.
Создайте матрицу размера n*m такую что:

- На границе матрицы будут стоять 1
- Внутри матрицы будут стоять 0

Сохраните матрицу в переменную Z.

In [124]:
n, m = map(int, input().split())
Z = np.zeros((n, m))
Z[:, 0] = 1
Z[:, -1] = 1
Z[0, :] = 1
Z[-1, :] = 1
Z

10 10


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 16

Имеется матрица Z

Добавьте вокруг имеющихся значений матрицы "забор" из 0.

Результат должен быть сохранён в ту же переменную Z.

Попробуйте использовать функцию https://numpy.org/doc/stable/reference/generated/numpy.pad.html?highlight=numpy%20pad#numpy.pad

In [134]:
Z = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

def pad_with(vector, pad_width, iaxis, kwargs):

    pad_value = kwargs.get('padder', 0)

    vector[:pad_width[0]] = pad_value

    vector[-pad_width[1]:] = pad_value



np.pad(Z, 1, pad_with)


array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

In [135]:
Z = np.pad(Z,(1, 1), 'constant', constant_values = 0)
# Z = numpy.pad(Z, 1, 'constant')

# 17

Что вернёт каждое из выражений?

In [137]:
np.inf > np.nan 

False

In [138]:
np.nan in set([np.nan]) 

True

In [139]:
np.isnan(np.nan) 

True

In [140]:
0 * np.nan 

nan

In [141]:
np.nan - np.nan 

nan

In [142]:
0.3 == 3 * 0.1 

False

In [143]:
np.nan == np.nan

False

In [145]:
n = np.nan
m = np.nan
print(id(n), id(m), sep='\n')
print(id(n) == id(m))
print(n == m)

140506605037296
140506605037296
True
False


# 18.1

Считайте число n.

Создайте диагональную матрицу размера n*n. На главной диагонали должны быть числа от 1 до n.

Сохраните матрицу в переменную Z.

In [173]:
n = int(input())
Z = np.diag((np.arange(1, n + 1)))
Z

3


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# 18.2

Считайте 2 числа:

- x - сдвиг для единственной ненулевой диагонали в матрице.
- k - верхняя граница для интервала чисел на диагонали (т.е. если k = 5, то на диагонали будут стоять числа 1, 2, 3, 4 и 5)

Договоримся о значениях x:

- x = 0 - это главная диагональ матрицы
- x<0 - диагональ сдвигается вниз на |x| ячеек (если x = -1, то первая не нулевая ячейка будет с координатами (1,0))
- x>0 - диагональ сдвигается вправо на |x| ячеек (если x = 1, то первая ненулевая ячейка будет с координатами (0,1))

Обратите внимание, что размер матрицы изменяется в зависимости от сдвига, т.к. вам надо уместить все числа от 1 до k!

Сохраните такую матрицу в переменную Z.
- 1 2
- -1 2
- 0 2

In [177]:
x, k  = map(int, input().split())
Z = np.diag((np.arange(1, k + 1)), k = x)
Z

1 2


array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

# 19 (21)


Считайте 2 числа: n, m.

Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.

- 0 - "чёрное"
- 1 - "белое"

Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0).

Матрицу сохраните в переменную Z.

In [191]:
n, m =  map(int, input().split())
Z = np.zeros((n, m))
Z[::2, 1::2] = 1
Z[1::2, ::2] = 1
Z

8 8 


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [193]:
Z = np.ones((n,m))
Z[::2, ::2] = 0
Z[1::2,1::2] = 0
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [195]:
Z = np.tile([[0.,1.],[1.,0.]], (1+n//2,1+m//2) )[:n,:m]
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 20

Если у нас есть матрица (или numpy массив большей размерности), то её можно представить в линейном виде:

Идея в том, что можно каждому элементу матрицы можно поставить в соответствие индекс.

Функция numpy.unravel_index проводит обратную операцию - по индексу элемента определяет его "координаты" в матрице.


Даны:

- индекс i
- numpy массив Z

Определите "координаты" элемента с индексом i в Z и выведите кортеж с координатами на печать.

In [200]:
i = 6
Z = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

np.unravel_index(i, np.shape(Z)) 

(1, 2)

# 22 Нормализация

Используйте формулу $x_n = (x -\mu) / \sigma$ ,

где

- x - старое значение
- x_n - новое значение
- $\mu$ - среднее значение (по всей матрице)
- $\sigma$ - стандартное отклонение (по всей матрице)

для того чтобы "нормализовать" матрицу.

In [4]:
Y = np.array([[1, 2],
              [2, 1]])

YY = np.array([[99, 11, 55],
               [33, 66, 99]])

Z = np.round((Y - np.mean(Y)) / np.std(Y), 2)
ZZ = np.round((YY - np.mean(YY)) / np.std(YY), 2)
ZZ

array([[ 1.19, -1.54, -0.17],
       [-0.85,  0.17,  1.19]])

# 24.1 Скалярное произведение векторов

Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и сохраните в переменную Z.

A и B могут содержать как int, так и float.

In [7]:
A = np.array([1.5, 2.5, 3.5])
B = np.array([4, 5, 6])

AA = np.array([1, 3, 5, 7, 9])
BB = np.array([-2, 4, -6, 8, -10])
np.dot(AA, BB)

# ввели с питона 3.5
Z = A@B
Z

39.5

# 24.2 Умножение матриц

Даны 2 матрицы: A и B.

Найдите произведение матриц и сохраните его в переменную Z.

Если найти произведение матриц невозможно, то запишите в Z строку: "Упс! Что-то пошло не так..."

In [9]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [11.5],
    [12.5],
    [13.5]
])

Z = A@B
Z

array([[ 77. ],
       [189.5]])

In [13]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [11.5, 12.5, 13.5]
])
try:
    Z = A@B
except:
    Z = "Упс! Что-то пошло не так..."

Упс! Что-то пошло не так...


# 25

Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.

In [34]:
Z = np.arange(11)

Z = np.where((Z>3)&(Z<9), -Z, Z)
# или
# Z[(3 < Z) & (Z < 8)] *= -1

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

# 26

Что выведет на печать код:

In [35]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


# 27

Предположим, Z - целочисленный вектор, например:

Z = np.array([1, 2, 3, 4, 5, 6, 7])

Какие из операций возможны (не приведут к ошибке)?

In [36]:
Z = np.array([1, 2, 3, 4, 5, 6, 7])

In [45]:
# Z/1/1

# Z<z>Z

# 1j*Z # комплексная единица

# Z**Z

# Z <- Z # знак "меньше" и унарный минус. Проверяется условие Z поэлементно меньше -Z

2 << Z >> 2 

array([ 1,  2,  4,  8, 16, 32, 64])

Если по простому:

$x << y =$ это тоже самое что и x * 2**y

$x >> y =$ тоже самое что и x // 2**y


# 28

Сопоставьте выражения и результат их выполнения

In [46]:
np.array(0) / np.array(0)

<ipython-input-46-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [47]:
np.array(0) // np.array(0)

<ipython-input-47-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [48]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

# 29

Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0

In [49]:
A = np.array([-3.1, -5.9, 0, 2.2, 9.8])

# медленный вариант
Z = np.where(A < 0, np.floor(A), np.ceil(A))

# быстрый вариант 
ZZ = np.copysign(np.ceil(np.absolute(A)), A)

array([-4., -6.,  0.,  3., 10.])

# 30

Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

Если пересечений нет, то вектор Z будет пустым.

In [50]:
A = np.array([0, 9, 7, 1, 3, 7, 5, 2, 5, 1])
B = np.array([3, 1, 3, 7, 4, 1, 8, 1, 1, 8])

np.intersect1d(A, B)

array([1, 3, 7])

In [51]:
A = np.arange(-5, 5)
B = np.array([9, -5, 2])

np.intersect1d(A, B)

array([-5,  2])

# 31

Suicide mode on

В Numpy можно предусмотреть различное поведение в случае ошибок (а не только то, что мы наблюдали в задаче 28). Для этого используется функция https://numpy.org/doc/stable/reference/generated/numpy.seterr.html

Отключите вывод всех ошибок (это довольно опасное поведение)

In [ ]:
# решение
np.seterr(all="ignore")

In [52]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [53]:
Z

array([inf])

# 32
Что можно сказать о выражении


In [54]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-54-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

# 33

Изучите работу с датами (https://docs.scipy.org/doc/numpy-1.15.0/reference/arrays.datetime.html) и выберите верные утверждения:


In [55]:
np.datetime64('nat')-1

numpy.datetime64('NaT')

In [56]:
np.datetime64('today') 

numpy.datetime64('2021-03-12')

In [57]:
np.datetime64('tomorrow') 

ValueError: Error parsing datetime string "tomorrow" at position 0

In [58]:
np.datetime64('today')-1 

numpy.datetime64('2021-03-11')

In [59]:
np.datetime64('yesterday')

ValueError: Error parsing datetime string "yesterday" at position 0

In [60]:
np.datetime64('nat')+1 

numpy.datetime64('NaT')

In [61]:
np.datetime64('nat')

numpy.datetime64('NaT')

In [62]:
np.datetime64('today')+1

numpy.datetime64('2021-03-13')

# 34

- 1-я входная строка - год (опционально месяц и день) в формате ISO начала отсчёта
- 2-я входная строка - год (опционально месяц и день) в формате ISO окончания отсчёта

Составьте список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).
Результат должен представлять из себя список дат в формате ISO.
Пример - 2005-02-25, где

- 2005 - год
- 02 - месяц
- 25 - день

Запишите результат в переменную Z

In [63]:
Z = np.arange(input(), input(), dtype='datetime64[D]')

2016-07
2016-08


In [64]:
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

# 36

Существует по крайней мере 5 способов получить из вектора случайных float чисел вектор чисел только с целой частью:

- Целочисленное деление и векторные операции
- Округление "вниз"
- Округление "вверх" и вычет 1 (важно, что этот способ работает только для "случайных" чисел. Если число УЖЕ целое, то такая манипуляция приведёт к получению числа на 1 меньше исходного, т.е. ошибке)
- Приведение к целочисленному типу
- "Усечение" или округление в сторону нуля с помощью функции https://numpy.org/doc/stable/reference/generated/numpy.trunc.html

In [65]:
Z = np.random.uniform(0,10,10)

#1
Z - Z%1

array([3., 9., 5., 5., 2., 2., 1., 5., 9., 7.])

In [66]:
#2
np.floor(Z)

array([3., 9., 5., 5., 2., 2., 1., 5., 9., 7.])

In [67]:
#3
np.ceil(Z)-1

array([3., 9., 5., 5., 2., 2., 1., 5., 9., 7.])

In [68]:
#4
Z.astype(int)

array([3, 9, 5, 5, 2, 2, 1, 5, 9, 7])

In [69]:
#5
np.trunc(Z)

array([3., 9., 5., 5., 2., 2., 1., 5., 9., 7.])

# 37.1

На вход подаётся 2 строки:

- 1-я строка содержит 2 натуральных числа: n, m
- 2-я строка содержит число k

Создайте матрицу размера n*m такую, что каждая её строка содержит числа от k до k+m-1 (с шагом 1).

Ответ запишите в переменную Z

3 5

0

In [90]:
n, m = map(int, input().split())
k = int(input())

Z = np.tile(np.arange(k, k+m, dtype=float), n).reshape((n, m))
Z

5 4
-5


array([[-5., -4., -3., -2.],
       [-5., -4., -3., -2.],
       [-5., -4., -3., -2.],
       [-5., -4., -3., -2.],
       [-5., -4., -3., -2.]])

# 37.2

На вход подаётся 2 строки:

- 1-я строка содержит 2 натуральных числа: n, m
- 2-я строка содержит число k

Создайте матрицу размера n*m такую, что каждый её столбец содержит числа от k до k+n-1 (с шагом 1).

Ответ запишите в переменную Z

In [93]:
n, m = map(int, input().split())
k = int(input())

Z = np.tile(np.arange(k, k+n, dtype=float), m).reshape((m, n)).T
Z

3 5
0


array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.]])

# 38

Переменная V содержит итерируемый объект.

Превратите его в одномерный numpy массив и сохраните в переменную Z. Массив будет содержать только числа типа float.

In [95]:
V = map(np.sin, range(10))
# V = range(10)
# V = {1:2, 3:4}

Z = np.fromiter(V, float)
Z

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

# 39.1 (деление отрезка на N+1 часть)

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Составьте список (numpy.array) из n точек на отрезке (start, stop), попарно равноудалённых друг от друга и от концов отрезка (т.е. разделите отрезок на n+1 часть). Округлите значения точек до 3 знака после запятой.

Результат сохраните в переменную Z.

In [103]:
start = int(input())
stop = int(input())
n = int(input())

Z = np.around(np.linspace(start, stop, num=n+2), 3)[1:-1]
ZZ = np.around(np.linspace(start, stop, n + 1, endpoint=False), 3)[1:]
ZZ

0
1
9


array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# 39.2

На вход подаются 3 числа (каждое с новой строки):

- start
- stop
- n

Составьте список из n точек на отрезке [start, stop] в геометрической прогрессии, включая start и stop.

Округлите значения точек до 3 знака после запятой.

Результат сохраните в переменную Z.

In [106]:
start = int(input())
stop = int(input())
n = int(input())

Z = np.geomspace(start, stop, num=n).round(3)
Z

1
1000
4


# 40

Считайте 2 числа:

- seed
- n

С помощью Numpy сгенерируйте n случайных чисел из интервала (0, 1) с фиксированным seed (https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html), отсортируйте их по возрастанию и сохраните в переменную Z.

In [108]:
seed = int(input())
n = int(input())

np.random.seed(seed)
Z = np.sort(np.random.random(n))
Z

5
5


[0.20671915533942642,
 0.22199317108973948,
 0.48841118879482914,
 0.8707323061773764,
 0.9186109079379216]